#KerasJson: keras/KERAS_dense_16x500x500x500x500x500x5.json
#KerasH5: keras/KERAS_dense_16x500x500x500x500x500x5_weights.h5
#KerasJson: keras/KERAS_mnist_cnn.json
#KerasH5:   keras/tmp_model.h5
#KerasH5:   keras/resnet50_model.h5
#KerasH5:   keras/KERAS_mnist_cnn.h5
#KerasJson:  keras/KERAS_ecal_cnn.json
#KerasH5:    keras/KERAS_ecal_cnn.h5
KerasJson:  keras/sho_model_arch.json
KerasH5:    keras/sho_model_weights.h5
#InputData: keras/KERAS_3layer_input_features.dat
#OutputPredictions: keras/KERAS_3layer_predictions.dat
OutputDir: shomodel
ProjectName: myproject
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5
Backend: Vivado

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 128
    Strategy: Resource
  LayerType:
    Dense:
      ReuseFactor: 128
      Strategy: Resource
      Compression: False
    Conv2D:
      ReuseFactor: 128
      Strategy: Resource
      Compression: False
    Conv2DMerge:
      ReuseFactor: 128
      Strategy: Resource
      Compression: False
